version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - mynet

  ftp_checker:
    build:
      context: ./data_retrieval/ftp_checker/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - FTP_CHECKER_SVC=localhost
      - FTP_CHECKER_PORT=5000

    ports:
      - 5021:5000
    networks:
      - mynet

networks:
  mynet:
    driver: bridge